- README.md
`RAILS_ENV=production` must go before the `bundle exec` or else:
```
bundler: command not found: RAILS_ENV=production
Install missing gem executables with `bundle install`
```
> Fixed type in example code in Readme

- lib/rack/cors.rb
- test/unit/cors_test.rb
As explained in
http://www.fastly.com/blog/best-practices-for-using-the-vary-header/
responses should ALWAYS include `Vary: Origin` if there's a chance for
the response to differ depending on the Origin header in the request.
This covers the case for when 2 requests for the same resource, one
including the Origin header and the other not including it, should have
different responses. If the Vary header doesn't mention Origin, then
intermediary caches (like any CDN) will cache the response (including
its headers) and will use it regardless of the request including the
Origin header or not.
This is to play nice with caches. Otherwise rack-cors can't be used with
caches in certain situations.
> Fixes bug where Vary header was omitted in certain occasions

- lib/rack/cors.rb
- test/unit/cors_test.rb
- test/unit/test.ru
This matches the way headers can bet set to `:any`, but for methods.
> Added ability to set resource methods to any

- lib/rack/cors.rb
- test/unit/cors_test.rb
- test/unit/test.ru
Setting ORIGIN header to nil makes Rack::Lint fail.
I also added Rack::Lint to test.ru to ensure that it is always compliant.
> Only use X-ORIGIN when defined.

- lib/rack/cors.rb
The previous implementation would allow an attack by submitting requests with
randomly-generated 'Access-Control-Request-Method' to fill the symbol table
of the server process. This is especially dangerous on Ruby < 2.2 because the
symbols will not be GCed, ever.
> Fix a potential symbol leak

- lib/rack/cors.rb
this removes the following Ruby warning:
```
rack-cors-0.4.0/lib/rack/cors.rb:336: warning: assigned but unused variable - x_origin
```
> remove unused variable

- README.md
`^$` match the start and end of lines. `\A\z` match the start and end of the whole string. This change makes the regexp syntax match the wording used in the security note in the README.
This closes issue #103 and demonstrates safer regex practices to any newer members of our community who may not yet be aware of the difference between `^$` and `\A\z`.
Like @danlo (author of issue #103) I don't think this is a big problem for rack-cors but I thought the change was worth it from a "leading by example" point of view.
Thanks for this gem and your time
/Eoin/
> Replace ^$ with \A\z in the README regexp examples

- README.md
Fixes an issue in the README where Rails 5 accepts class rather than string.
> Add change where Rails 5 accepts class rather than string.

- lib/rack/cors.rb
- test/unit/cors_test.rb
Browsers send null origins when an iframe contains html code for its
source instead of a URL. This means that websites who used rack-cors and
allowed "file://" were open to attacks from malicious pages that used
this fact to send "null" origins.
> Keep null origins from masquarding as "file://"

- README.md
- lib/rack/cors.rb
- test/unit/cors_test.rb
- test/unit/insecure.ru
This PR fixes #126.
Main changes:
* Specifying a wildcard origin in combination with 'allow credentials' isn't allowed anymore.
* `credentials` defaults to true iff the specified origin is not the wildcard.
* Origin mirroring only occurs if no origin wildcard was used.
> Prevent insecure CORS configurations

- test/unit/cors_test.rb
Created a gem that required the same logging. 
I am using `single_cove` and it showed that there was no test coverage for `Logger`
> Add test coverage for Logger

- lib/rack/cors.rb
- test/unit/cors_test.rb
Headers in Rack may be arrays of values. If that is the case with the vary header, then rack-cors will fail when attempting to `split` it.
This change handles the vary header when it is both a string and an array.
> Handle arrays of vary headers

- lib/rack/cors.rb
- rack-cors.gemspec
- test/unit/cors_test.rb
Rack-cors used to set `Content-Type` header to `text/plain` on preflight requests. It was added [9 years ago](https://github.com/cyu/rack-cors/commit/7b67da387a6efd9ed0928a727e61dd52578c1f61) because rack spec required it at that time.
In 2012, rack spec was [updated](https://github.com/rack/rack/commit/2138f0b9ad37e625b48e4214fa24126de7917335), so `Content-Type` header is no longer required.
The reason why someone would need for this header to be removed is new [CORB protection](https://www.chromium.org/Home/chromium-security/corb-for-developers). If you check its description [here](https://fetch.spec.whatwg.org/#corb), you'll see that response to OPTIONS request with `text/plain` header will be blocked. Blocking does not affect any functionality, it just shows an error in Chrome …
> Remove Content-Type header from preflight OPTIONS response

- README.md
Based on https://github.com/cyu/rack-cors/issues/70#issuecomment-75392790
I wanted to figure out how to add a host constraint to a resource. I missed the `:if` option when skimming the README, so I had to search the issues. I think this would be a helpful tip
> Add an :if example to the README

- README.md
`Bundler.require` automatically loads lib/rack/cors.rb even if there is no :require option.
This can be verified by the following code:
```rb
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "rack-cors"
end
puts defined?(Rack::Cors) #=> constant
```
cf. https://guides.rubygems.org/name-your-gem/
> Remove unnecessary :require option from Gemfile example

- lib/rack/cors.rb
Browsers cap the value of Access-Control-Max-Age, Chromium being the most aggressive at 2 hours:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
https://cs.chromium.org/chromium/src/services/network/public/cpp/cors/preflight_result.cc?rcl=49e7c0b4886cac1f3d09dc046bd528c9c811a0fa&l=28-31
It sounds logical to set a default value that all browsers will honor.
> Reduce default max_age to a more sensible value

- README.md
The rails 4 and rails 3 examples are no longer here, replaced with rails 5 example.
> Fix example link in README

- README.md
This explanation is most valuable to folks who are seeing anchors for the first time, so we can use our example again, to put the usage into context.
> README: Example for start & end string anchors

- README.md
Document workaround discussed in https://github.com/cyu/rack-cors/issues/100
Here's what the Markdown once rendered by GitHub:
> Document how to use custom protocols (chrome-extension://, etc.)

- README.md
I found a missing configuration note for when create Rails application with `--api` option.
Is not necessary?
> Add configuration note to README.md

- README.md
The link was down + showing security warning messages on Chrome.
I therefore changed the link to the corresponding MDN resource, let me know if this proposed link is ok.
> [README] Update readme link

- test/unit/cors_test.rb
The support for `require 'mocha/setup'` is long time deprecated and was removed in Mocha 2.0:
https://github.com/freerange/mocha/commit/642a0ff4
> Mocha 2.0+ / Minitest 5.19+ compatibility

- lib/rack/cors/resource.rb
- test/unit/cors_test.rb
- test/unit/test.ru
This is minimal fix for issue #269 
It's just adding '$'  to special_chars in Ressource.compile
I have added a testcase too
> Escape $ in ressource paths compile

- .gitignore
- CHANGELOG.md
- rack-cors.gemspec
Adding the CVE ids to the changelog is the most important part here, IMO. Please feel free to ignore the other two changes.
> Various docs for 2.0.2

- README.md
The first one is not working anymore.
> docs(readme): fix `rake middleware` to `rails middleware`

- rack-cors.gemspec
I noticed that you are already on GitHub Sponsors. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.
> Add funding_uri to gemspec
